name: CI

on: pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: default lint
    steps:
      - name: Check out source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
        with:
          bundler-cache: true

      - name: Run RuboCop
        run: bin/rubocop --format github --format clang

      - name: Cache RBS collection
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .gem_rbs_collection
          key: rbs-collection-${{ runner.os }}-${{ hashFiles('rbs_collection.lock.yaml') }}
          restore-keys: |
            rbs-collection-${{ runner.os }}-

      - name: Install RBS collection
        run: bin/rbs collection install

      - name: Run RBS validation
        run: bin/rbs -I sig validate

      - name: Run Typecheck
        run: bin/steep check

  version-matrix:
    name: Generate version matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.version-matrix.outputs.matrix }}
    steps:
      - name: Check out source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
        with:
          bundler-cache: false

      - name: Generate version matrix
        id: version-matrix
        run: bin/version-matrix

  test:
    needs: version-matrix
    strategy:
      matrix: ${{ fromJSON(needs.version-matrix.outputs.matrix) }}
      max-parallel: 8
    name: Ruby ${{ matrix.ruby }} | PG ${{ matrix.pg }} | Active Record ${{ matrix.activerecord }}
    runs-on: ubuntu-latest
    env:
      ACTIVERECORD_VERSION: ${{ matrix.activerecord }}
      PG_VERSION: ${{ matrix.pg }}
    services:
      postgres:
        image: postgres:18@sha256:41da01536bc3ae26308cefb0c57235e7488001360bdb15191eb0b7955b570299
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: workload_identity_test
        ports:
          - 25432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Check out source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false

      - name: Update Gemfile.lock
        run: bundle lock --update activerecord pg railties

      - name: Install gems
        uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run unit tests
        run: bin/rake test:unit

      - name: Run acceptance tests
        run: bin/rake test:acceptance

      - name: Upload test coverage
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-ruby-${{ matrix.ruby }}-pg-${{ matrix.pg }}-activerecord-${{ matrix.activerecord }}
          path: coverage/.resultset.json
          include-hidden-files: true

  test-results:
    name: Check test results
    if: always()
    needs:
      - version-matrix
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Check test results
        env:
          TEST_RESULT: ${{ needs.test.result }}
        run: test "$TEST_RESULT" = "success"

      - name: Check out source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Download test coverage
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: coverage-*

      - name: Collate test coverage
        run: bin/rake coverage:collate

      - name: Upload test coverage
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage
          path: coverage

      - name: Report test coverage
        uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9 # v1.5.1
